version: '2'
services:
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
    webapp:
        build:
           context: .
           dockerfile: WarDockerfile 
        image: tomcat:wardemo
        ports:
           - "8083:8080"
        links:
            - mysql
